### ISSUE TITLE
Example ex05_ard_pages touch not working 

### ISSUE THREAD

**Issue by Afantor** [ImpulseAdventure/GUIslice#154]
ex05_ard_pages.ino not working good, but I tried your example ex07_ard_slider.ino is work good.

My GuiSlice Configuration:
config.h has /configs/esp-tftespi-default-xpt2046_int.h enabled
config_arg.h has DRV_DISP_TFT_ESPI enabled, & DRV_TOUCH_TFT_ESPI enabled
ADATOUCH_PRESS_MIN/MAX settings. reset after a recalibration of screen(diag_ard_touch_calib.ino).

Hardware of device
ESP32 development board
2.4" TFT touch_ILI9341 display(XPT2046)

**Comment by ImpulseAdventure** [comment]
Hi there @Afantor !

Thanks for providing your configuration. I just re-checked my **ESP32** + **2.4" TFT ILI9341** with **XPT2046** and **ex05** appeared to be working correctly in my test setup. It is a bit surprising to hear that your touch works in ex07 but not ex05. I wonder if you are seeing very noisy touch readings...

Please try the following:
- Close down the Arduino IDE
- Edit your config to enable/uncomment `DBG_TOUCH` (near the end of the file)
- Reopen Arduino IDE, open the serial monitor
- Re-run **ex05**

You should see yellow boxes near where the touch presses occur. If possible use a stylus to touch the display. Do the yellow markers line up with your touch presses?

If not:
- Please restart the program and touch the word "Demo" on the screen and ideally attach a photo of what you see. I am recommending that you press at the middle of the "Demo" word so that I can compare how the touch presses are mapping on your display.
- Please also attach the output from your serial monitor window. (You should see a number of `DBG:` lines reported).

Many thanks!
