### ISSUE TITLE
XRingGauge does not draw correctly at higher quality

### ISSUE THREAD

**Issue by dbonnell** [ImpulseAdventure/GUIslice#172]
### Describe the bug
If the quality is increased using `gslc_ElemXRingGaugeSetQuality`, the gauge only partially renders.  For example, if you increase the quality from the default of 72 to 144, it only renders half a circle.  With quality of 180, only around 1/6th of a circle is used.

### Device hardware
- *MCU*: ATmega2560
- *Display with link*: mcufriend touch shield TFT 2.4"
- *GUIslice config selected*: `ard-shld-mucfriend`

### Expected behavior
Gauge renders full circle, at higher quality (e.g. quality of 180 => 180 sectors of 2 degrees each)

### Initialization messages
```
GUIslice version [0.13.0]:
- Init display handler [ADA_MCUFRIEND] OK
- No touch handler enabled
DBG: InvRgnScreen
DBG: InvRgnPage: Page=0 (0,0)-(-1,-1)
DBG: InvRgnPage: Page=0 (0,0)-(-1,-1)
DBG: InvRgnPage: Page=0 (0,0)-(-1,-1)
DBG: PageRedrawGo() InvRgn: En=1 (0,0)-(319,239) PageRedraw=1
DBG: redraw inc=0 last=0 cur=93 segs 0..360


RingDraw: Val=93 ValLast=0 PosMin=0 PosMax=100 Q=180
RingDraw:  Inactive start=360 end=-320
FillSector: StepInd=0 SegInd=-2 (-2..22)
FillSector: StepInd=1 SegInd=-1 (-2..22)
FillSector: StepInd=2 SegInd=0 (-2..22)
FillSector: StepInd=3 SegInd=1 (-2..22)
FillSector: StepInd=4 SegInd=2 (-2..22)
FillSector: StepInd=5 SegInd=3 (-2..22)
FillSector: StepInd=6 SegInd=4 (-2..22)
FillSector: StepInd=7 SegInd=5 (-2..22)
FillSector: StepInd=8 SegInd=6 (-2..22)
FillSector: StepInd=9 SegInd=7 (-2..22)
FillSector: StepInd=10 SegInd=8 (-2..22)
FillSector: StepInd=11 SegInd=9 (-2..22)
FillSector: StepInd=12 SegInd=10 (-2..22)
FillSector: StepInd=13 SegInd=11 (-2..22)
FillSector: StepInd=14 SegInd=12 (-2..22)
FillSector: StepInd=15 SegInd=13 (-2..22)
FillSector: StepInd=16 SegInd=14 (-2..22)
FillSector: StepInd=17 SegInd=15 (-2..22)
FillSector: StepInd=18 SegInd=16 (-2..22)
FillSector: StepInd=19 SegInd=17 (-2..22)
FillSector: StepInd=20 SegInd=18 (-2..22)
FillSector: StepInd=21 SegInd=19 (-2..22)
FillSector: StepInd=22 SegInd=20 (-2..22)
FillSector: StepInd=23 SegInd=21 (-2..22)
RingDraw: Active   start=0 end=-320 astart=0 arange=360
FillSector: StepInd=0 SegInd=0 (0..22)
FillSector: StepInd=1 SegInd=1 (0..22)
FillSector: StepInd=2 SegInd=2 (0..22)
FillSector: StepInd=3 SegInd=3 (0..22)
FillSector: StepInd=4 SegInd=4 (0..22)
FillSector: StepInd=5 SegInd=5 (0..22)
FillSector: StepInd=6 SegInd=6 (0..22)
FillSector: StepInd=7 SegInd=7 (0..22)
FillSector: StepInd=8 SegInd=8 (0..22)
FillSector: StepInd=9 SegInd=9 (0..22)
FillSector: StepInd=10 SegInd=10 (0..22)
FillSector: StepInd=11 SegInd=11 (0..22)
FillSector: StepInd=12 SegInd=12 (0..22)
FillSector: StepInd=13 SegInd=13 (0..22)
FillSector: StepInd=14 SegInd=14 (0..22)
FillSector: StepInd=15 SegInd=15 (0..22)
FillSector: StepInd=16 SegInd=16 (0..22)
FillSector: StepInd=17 SegInd=17 (0..22)
FillSector: StepInd=18 SegInd=18 (0..22)
FillSector: StepInd=19 SegInd=19 (0..22)
FillSector: StepInd=20 SegInd=20 (0..22)
FillSector: StepInd=21 SegInd=21 (0..22)
```

### Additional info
In `gslc_DrawFillSectorBase` is calculates the integer step angle, `nStepAng = 360 / nQuality`.  So the first issue is that if you don't use a factor of 360, rounding errors will mess things up.  So a quality of 144 isn't going to work, but 180 should.

**Comment by ImpulseAdventure** [comment]
Hi David --

The side-effects of #171 may have caused additional issues, but as you have seen, the higher quality settings (ie. 120, 180, 360) currently produce incorrect rendering. Similar to #171, this was due to an integer range issue that overflows in the higher precision modes. I have now checked in a fix that should allow the higher quality modes to render correctly.

As you have noted, the quality setting supports a few discrete values (more specifically, the number of degrees that make up each sector of a gauge rendering). In order to ensure we don't consume precious FLASH memory pulling in the floating point libraries, the quality setting utilizes integer math, hence the discrete values. I have updated the documentation to list out the available setting values, ie: 360, 180, 120, 90, 72, 60, 45, 40, 36, etc.

Please give the latest version a try and let me know if it works better.

**Comment by dbonnell** [comment]
Tested at Q=180, worked fine, looks much smoother.  Thank you for the quick turnaround.
