### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by Beginner69** [ImpulseAdventure/GUIslice#526]
I'm really a novice and don't really understand how Github works. 
I searched for the library "Key .h" and there I can find and download a raw file.
But how can I use that rawfile as a library in Arduino.
Maybe a stupid question but as a 70 year old it is difficult for me but I still try to find a solution to make a flawless sketch in Arduino. I always get this error message now: 
C:\Users\claes\Documents\Arduino\libraries\Adafruit_AD569x_Library/Keypad.h:36:10: fatal error: Key.h: No such file or directory
 #include "Key.h"
          ^~~~~~~

Can someone please help me with this.

**Comment by Pconti31** [comment]
@Beginner69 First you are only 70?  I wish I was that young AGAIN...

Now on the surface it would seem Keypad.h is in Adafruit_AD569x_Library folder which it should not be since that file doesn't exist as part of this package.  Did you move it there??? In any case, delete any files not part of the released  Adafruit_AD569x_Library.

If you are using a keypad library like for example: [Keypad](https://github.com/Chris--A/Keypad)
Then all of its files should be inside Arduino\libraries\Keypad this is why you are getting compile errors.

Now as a normal procedure when you load a new library you should **first try running any example programs** for that package.

So for the Keypad library I mentioned above first get _examples/HelloKeypad.ino_ to work before using it in a more complex app using other devices.  While [Adafruit_AD569x(https://github.com/adafruit/Adafruit_AD569x) has _examples/AD5693_test.ino_
 All Arduino libraries should comes with at least one example program. 

Not meaning to be rude but beginner questions like these should be asked in the [Arduino Forum](https://forum.arduino.cc/) since Github and **GUIslice issues** in particular isn't setup as a complex question and answer forum, nor could we handle the volume of questions that can arise otherwise.
Paul--
