### ISSUE TITLE
Avoid reloading entire page and background when pressing a button

### ISSUE THREAD

**Issue by Pconti31** [ImpulseAdventure/GUIslice#89]
The full page refresh is most noticeable when you have many image buttons loaded from an SD card on a page.  Pressing one will cause the page to reload with the button now set for glow, then immediately reloads page again and changes button back to normal image.

**Comment by ImpulseAdventure** [comment]
The quick answer is that one can generally avoid full-page redraws by ensuring that updated elements have their FILL parameter set to true (ie. Not transparent).

By current defaults, most created elements default to FILL=true with the exception of `ElemCreateBtnImg()` and `ElemCreateImg()`. If you are using such elements, try calling `ElemSetFillEn(true)` to ensure transparency is not enabled, and then set the `colFill` to match the background color.

### Details
For most displays, GUIslice will support partial page redraws. When performing a partial page redraw, only the items that have been marked as needing update are redrawn. However, if an updated element is marked as partly transparent (ie. The FILL_EN parameter is false), then the entire page is redrawn, since it is possible that the background and/or partially obscured elements may need to be redrawn.

I am considering making the above image element types default to FILL_EN=true as that may be more consistent and provide better performance as a default. If transparency is required (eg. Image with transparency over a background image), the `ElemSetFillEn(false)` can still be applied.

There is an outstanding TODO to consider detecting the subset of elements below a modified transparent element’s bounding box, but this has not been implemented.

Let me know if this works for your scenario.

**Comment by Pconti31** [comment]
Works Great.
Thanks!
